### ISSUE TITLE
Typo in readme.

### ISSUE THREAD

**Issue by robodude666** [vba-blocks/vba-blocks#12]
The readme states that `yarn build:cli` could be ran; however, cli is not valid.

It also claims `yarn build:addin` however the actual command is `addins`.

**Comment by connerk** [comment]
Easy PR! ;)

**Comment by robodude666** [comment]
I don't know if Tim's intent was to have a `build:cli` option and name it `addin` instead of `addins`. Figured I'd rather report it and let timhall decide what he wants the yarn commands to be.

**Comment by timhall** [comment]
Yeah, the instructions were pretty old, should be mostly fixed now
