### ISSUE TITLE
CLI `build` error - cannot compile xlsm (printersettings.bin)

### ISSUE THREAD

**Issue by connerk** [vba-blocks/vba-blocks#13]
I initialized an existing project for use with blocks using the CLI.

```powershell
vba-blocks new <project name>
cd <project name>
vba-blocks add-target xlsm --from "<old path>.xlsm"
```

when I execute 
```powershell
vba-blocks build
```

it results in
```powershell
ERROR Failed to import project for target "Account Comparison Tool"

10201: Failed to open document (C:\Users\kevin conner\.vba-blocks\staging\vba-blocks-10616Bykg9HuRg02O\Account Comparison Tool.xlsm)
```

if I open the file defined, excel asks if I want to repair it. after saying yes, these are what it repaired

![image](https://user-images.githubusercontent.com/1771679/44820831-8e4b7c80-aba7-11e8-8cf1-82817bc142de.png)

the workbook had only one print range in the name manager. I deleted it but still got the error.

the workbook has six sheets. 

when I search for the word `print` in the target folder four of the sheets `<sheetname>.xml.rels` files pop, not all six:
![image](https://user-images.githubusercontent.com/1771679/44821351-f8fdb780-aba9-11e8-80e0-38983f84a990.png)

note the `Target="../printerSettings/printerSettings[1].bin"/>`

there is a `../../PrinterSettings` folder from the file's position. it is empty
![image](https://user-images.githubusercontent.com/1771679/44821476-b38dba00-abaa-11e8-8b2d-afb57726e812.png)

if I remove these `<Relationship/>` tags, it will compile.

__could it be that all `.bin` files are being filtered out of the export?__

**Comment by timhall** [comment]
Hmm, yeah all bin files are being filtered out when it should just be the vba project. I'll see what I can do.

**Comment by timhall** [comment]
Fixed in https://github.com/vba-blocks/vba-blocks/commit/a71517b5cb1ee23736eb695b661b4ea9d54498ce
