### ISSUE TITLE
unable to install 0.0.0 with msi file

### ISSUE THREAD

**Issue by connerk** [vba-blocks/vba-blocks#16]
![image](https://user-images.githubusercontent.com/1771679/46959983-3cc15900-d052-11e8-8cc0-236d3101727e.png)

is there a log file somewhere I can include?

**Comment by timhall** [comment]
Crap, of course I see this after pushing out v0.1.0. I'm not familiar with logging with msi, I'll dig in and see what I can find. Thanks for trying it!

**Comment by timhall** [comment]
Ok, I've temporarily ignored errors thrown during the post-install actions. It's just for installing the add-in which isn't required at the moment. I added some minimal logging to start figuring out what is wrong. @connerk or @retailcoder can you try the install again and then look in your temp folder for vba-blocks.log (Mine is located at `C:/Users/USER/AppData/Local/Temp/vba-blocks.log`)?

**Comment by connerk** [comment]
it's a go for me (install anyhow).
Thanks Tim!

**Comment by connerk** [comment]
functions also all work.

**Comment by retailcoder** [comment]
works for me as well.

So... I managed to initialize a new project, make edits, export the source, and commit changes - I'm a little fuzzy on what the next steps are... how does "sharing packages" work?
Is there a `vba-blocks install <package>` command on the roadmap? I feel like I'm missing a piece of the puzzle...

**Comment by connerk** [comment]
I suppose this is safe to close by now. 🎂

**Comment by timhall** [comment]
Yep! Phew, quite a bit of cobwebs to clear out post new baby, but the new release is out. I'm hoping I've gotten everything sorted so that more rapid releases can take place now.
