### ISSUE TITLE
Can't install v.0.1.0?

### ISSUE THREAD

**Issue by retailcoder** [vba-blocks/vba-blocks#20]
Hitting a roadbump on step 1 of [#installation](https://github.com/vba-blocks/vba-blocks#installation) here:

!["There is a problem with this Windows Installer package"](https://user-images.githubusercontent.com/5751684/47129264-96986d80-d262-11e8-8843-080d1e0ef205.png)

Windows 10 Pro version 1803 (build 17134.345), local admin

**Comment by retailcoder** [comment]
linking #16

**Comment by timhall** [comment]
This is the same issue as #16 I'll update it there
