### ISSUE TITLE
vba-blocks cli alias

### ISSUE THREAD

**Issue by connerk** [vba-blocks/vba-blocks#21]
`vba-blocks` is going to get really tedious to type. 
can we add a native alias of `vba` since _that's_ not likely to ever have a different command line use!

**Comment by timhall** [comment]
I was thinking the same thing! I was a little nervous about camping on a name like that, I'll have to take another look at Microsoft's trademarks and such. I'm definitely for it.

**Comment by timhall** [comment]
This is done in v0.2.0, it's so nice!
