### ISSUE TITLE
Why does vba-block.toml need to be edited manually?

### ISSUE THREAD

**Issue by retailcoder** [vba-blocks/vba-blocks#24]
After running `vba-blocks export`, the CLI tool works its magic, and then issues the following message:

> The following changes need to be applied to vba-block.toml:
>
> Add the following to the [src] section:
>  {classname} = "src/{classname.cls}"

Since the tool knows what needs to change and where... I suppose it could perform these changes automatically, no?

**Comment by timhall** [comment]
This is definitely planned. I was running into issues finding a suitable approach that didn't mangle any existing comments / formatting in the manifest.

**Comment by retailcoder** [comment]
Would it be overkill to formalize the syntax with an Antlr4 grammar? Then you could alter the parse tree at will, pretty much like Rubberduck does (except with a *much* simpler tree 😉)..

**Comment by timhall** [comment]
Closed by #39 and released in v0.3.0
